---
version: '3.8'
services:

  dht_api:
    build: ./
    ports:
      - "127.0.0.1:8000:8000"
    links:
      - torproxy
      - minio
    depends_on:
      - torproxy
      - minio
    environment:
      - SOCKS_PROXY_URL=socks5://torproxy:9050
      - DB_FILE=/data/db.sqlite
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=eik1er3iebe6Roo2tuSootho
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://minio:9000
      - AWS_BUCKET_NAME=dht-api
    volumes:
      - ./data/dht_api:/data

  torproxy:
    image: dperson/torproxy
    restart: unless-stopped
    environment:
      - TORUSER=root

  ## XXX Uncomment this and create TUNNEL_TOKEN=<token> in .env file to enable
  ## Cloudflare tunnel
  # tunnel:
  #   container_name: cloudflared-tunnel
  #   image: cloudflare/cloudflared
  #   restart: unless-stopped
  #   depends_on:
  #     - dht_api
  #   links:
  #     - dht_api
  #   command: tunnel --no-autoupdate run --proxy-address dht_api --proxy-port 8000
  #   env_file: .env

  minio:
    image: minio/minio:latest
    volumes:
      - ./data/minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: eik1er3iebe6Roo2tuSootho
      MINIO_BUCKET_NAME: dht-api
    entrypoint: sh
    command: -c 'mkdir -p /data/dht-api && minio server /data'
