---
version: '3.8'
services:

  dht_api:
    build: ./
    ports:
      - "8000:8000"
    links:
      - torproxy
    environment:
      - SOCKS_PROXY_URL=socks5://torproxy:9050

  torproxy:
    image: dperson/torproxy
    restart: unless-stopped
    environment:
      - TORUSER=root
